version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: campusq_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: campusq_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: campusq_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgrespassword@db:5432/campusq_db
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: campusq_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: